shell_command:
  update_hacs_download_source: sh /config/replace_hacs_download_mirror.sh
  
automation:
  - alias: HA启动自动更新HACS下载源
    trigger:
      - platform: homeassistant
        event: start
    action:
      - service: shell_command.update_hacs_download_source
