notify:
  description: QQ邮件通知提醒
  fields:
    type: 
      description: '【非必填】state: 显示全部实体状态' 
      example: state
    email:
      description: 【非必填】如果不填，发送给自己
      example: '635147515@qq.com'
    title:
      description: 【必填】邮件标题
      example: '邮件标题'
    message:
      description: 【非必填】要提醒的文字（可以为HTML格式和使用系统模板）
      example: '<b>当前时间： {{now()}} </b>'
    data:
      description: 通知参考链接：https://www.home-assistant.io/integrations/html5/
      example: ''