sensor.date:
  friendly_name: 日期
sensor.time:
  friendly_name: 时间
sensor.connected_clients:
  friendly_name: 客户端数量
sensor.disk_use_percent:
  friendly_name: 磁盘使用占比
sensor.disk_use:
  friendly_name: 磁盘使用
sensor.disk_free:
  friendly_name: 磁盘空闲
sensor.memory_use_percent:
  friendly_name: 内存使用占比
sensor.memory_use:
  friendly_name: 内存使用
sensor.memory_free:
  friendly_name: 内存空闲
sensor.swap_use_percent:
  friendly_name: 交换分区使用占比
sensor.swap_use:
  friendly_name: 交换分区使用
sensor.swap_free:
  friendly_name: 交换分区空闲
sensor.processor_use:
  friendly_name: 处理器使用
sensor.last_boot:
  friendly_name: 开机时间
sensor.cpu_temperature:
  friendly_name: CPU温度
sensor.network_in_eth0:
  friendly_name: 网络下载eth0
sensor.network_out_eth0:
  friendly_name: 网络上传eth0
sensor.network_throughput_in_eth0:
  friendly_name: 网络下载速度eth0
sensor.network_throughput_out_eth0:
  friendly_name: 网络上传速度eth0
sensor.packets_in_eth0:
  friendly_name: 数据包接收
sensor.packets_out_eth0:
  friendly_name: 数据包发送
sensor.ipv4_address_eth0:
  friendly_name: IPV4地址eth0
sensor.ipv6_address_eth0:
  friendly_name: IPV6地址eth0
input_boolean.xiao_mi_tai_deng: {}
sensor.humidity:
  device_class: humidity
